config/routes.rb
Fithardware::Application.routes.draw do
  root to: "computers#index"
  get "guides", to: "pages#guides"
  get "about", to: "pages#about"

  devise_for :users

  resources :hulls,
            :power_supplies,
            :rams,
            :hdds,
            :ssds,
            :optical_drives,
            :motherboards,
            :cpus,
            :cpu_coolers,
            :video_cards do
    collection do
      post :filter
      get :filter
    end
  end

  resources :users do
    resources :computers
  end

  resources :computers do
    resources :hulls,
              :power_supplies,
              :rams,
              :hdds,
              :ssds,
              :optical_drives,
              :motherboards,
              :cpus,
              :cpu_coolers,
              :video_cards,
              only: [:index, :filter] do

      member do
        post :add_to
        post :remove_from
      end
      collection do
        post :filter
        get  :filter
      end
    end

    member do
      post :publish
    end
  end

  

end

app/models/hull.rb
# Because of word 'Case' is reserved by Ruby, computers case entity will be named as Hull
class Hull < Hardware

  POWER_SUPPLY_POSITIONS = %w(Vertical Horizontal Outer)

  ORDERED_FIELDS_FOR_FILTERS = [:amazon_price, :manufacturer, :form_factors, :power_supply_power, :power_supply_position,
                                :number_of_storage_slots, :number_of_optical_drives, :number_of_front_usb, :front_usb3,
                                :front_mic, :front_headphone, :front_fire_wire, :power_supply_down, :video_card_max_length,
                                :cpu_cooler_max_height]

  field :number_of_storage_slots, type: Integer, default: 0
  field :number_of_optical_drives, type: Integer, default: 0
  field :video_card_max_length, type: Integer, default: 250
  field :cpu_cooler_max_height, type: Integer, default: 140
  field :form_factors, type: Array
  field :hackintosh_compatible, type: Boolean, default: true
  field :power_supply_power, type: Integer, default: 0
  field :power_supply_position, type: String, default: 'Horizontal'
  field :number_of_front_usb, type: Integer, default: 2
  field :front_usb3, type: Mongoid::Boolean
  field :front_mic, type: Mongoid::Boolean, default: false
  field :front_headphone, type: Mongoid::Boolean, default: false
  field :front_fire_wire, type: Mongoid::Boolean, default: false
  field :power_supply_down, type: Mongoid::Boolean, default: false

  belongs_to :power_supply, dependent: :destroy
  has_many :computers
  
  validates_presence_of :form_factors
  validates_inclusion_of :power_supply_position, in: POWER_SUPPLY_POSITIONS
  validate :form_factor_validator

  [:number_of_storage_slots, :number_of_optical_drives, :form_factors, :power_supply_position, :number_of_front_usb].each do |field_symbol|
    scope "with_#{field_symbol}".to_sym, ->(arguments) { any_in(field_symbol => arguments) }
  end

  [:front_mic, :front_headphone, :front_fire_wire, :front_usb3].each do |field_symbol|
    scope "with_#{field_symbol}".to_sym, where(field_symbol => true)
  end

  scope :with_power_supply_power, ->(min, max) {between(:power_supply_power => min..max)}


  before_save do |document|
    if document.power_supply_power > 0 && document.power_supply.nil?
      document.power_supply = PowerSupply.create({manufacturer: document.manufacturer, product_name: "Hull's #{document.product_name} Power Supply",
                                                  image: document.image, power: document.power_supply_power, number_of_6_pin: 1,
                                                  number_of_6_2_pin: 1, number_of_sata_connectors: 3})
    end
  end

  def self.computer_compatible(computer)
    collection = self
      if computer.present?
        without_supplies = collection.exists(:power_supply => false)
        if computer.power_supply.present?
          collection = without_supplies
        else
          collection_supplies = collection.pluck(:power_supply)
          compatible_supplies = PowerSupply.in(id: collection_supplies).computer_compatible(computer)

          collection = collection.or({:power_supply.in => compatible_supplies.to_a.map(&:id)}, {:id.in => without_supplies.to_a.map(&:id)})
        end

        collection = collection.any_in(:form_factors => computer.motherboard.form_factor) if computer.motherboard.present?

        if computer.cpu_coolers.present?
          max_height = computer.cpu_coolers.to_a.map{|c| c.unpacked_height}.max
          collection = collection.gt(:cpu_cooler_max_height => max_height)
        end

        if computer.video_cards.present?
          max_vc_length = computer.video_cards.to_a.map{|vc| vc.unpacked_length}.max
          max_vc_width = computer.video_cards.to_a.map{|vc| vc.unpacked_width}.max

          collection = collection.and({:video_card_max_length.gt => max_vc_length },
          {:unpacked_width.gt => (max_vc_width * Computer::MARGIN_OF_SIZE_FITTING)})
        end

        collection = collection.gte(:number_of_storage_slots => computer.necessary_sata_ports)
        collection = collection.gte(:number_of_optical_drives => computer.optical_drives.count)
        collection = collection.where(:hackintosh_compatible => true) if computer.hackintosh_compatible
      end
    return collection
  end

  def self.filter_values
    values = self.standard_filter_values
    self.values_min_max(:power_supply_power, values)

    [:number_of_storage_slots, :number_of_optical_drives, :form_factors, :power_supply_position, :front_usb3, :front_mic,
     :front_headphone, :front_fire_wire].each do |field_symbol|
      temp_values = self.distinct(field_symbol)
      temp_values.reject! { |v| v.blank? }
      # If there is only one option, the choice is an illusion
      if temp_values.present? && temp_values.length > 1
        values[field_symbol] = temp_values.sort_by! { |e| e.to_s.downcase }
      end
    end
    return values
  end

  def fetch_yandex_features(all_features)
    self.power_supply_power = value_from_dimension_string all_features['Блок питания']
    self.power_supply_down = all_features['Блок питания внизу'].present?
    self.form_factors = all_features['Форм-фактор'].gsub(/mATX|Mini-ITX/, 'mATX'=>'microATX', 'Mini-ITX'=>'mini-ITX').split(', ')

    front_panel = all_features['Разъемы на лицевой панели']
    self.front_headphone = front_panel.include? 'наушники'
    self.front_mic = front_panel.include? 'микрофон'
    self.number_of_front_usb = front_panel.split('USB x')[1].first.to_i
    self.front_usb3 = front_panel.include? 'USB 3.0'
    self.front_fire_wire = front_panel.include? 'FireWire'

    case all_features['Расположение блока питания']
      when 'горизонтальное'
        self.power_supply_position = 'Horizontal'

      when 'вертикальное'
        self.power_supply_position = 'Vertical'

      else
        self.power_supply_position = 'Outer'
    end

    self.number_of_storage_slots = all_features['Число внутренних отсеков 3,5"'].to_i
    self.number_of_optical_drives = all_features['Число отсеков 5,25"'].to_i
    self.cpu_cooler_max_height = value_from_dimension_string all_features['Максимальная высота процессорного кулера'] || self.cpu_cooler_max_height
    self.video_card_max_length = value_from_dimension_string all_features['Максимальная длина видеокарты'] || self.video_card_max_length

    return self
  end



  private

  def form_factor_validator
    form_factors.each do |form_factor|
      errors.add(:form_factors, "Format doesn't exist") unless Motherboard::POSSIBLE_FORM_FACTORS.include? form_factor
    end
  end
end

app/controllers/hulls_controller.rb
class HullsController < HardwareController
  # For compatibility with CanCan we must manually set hardware to prevent triggering of it's getter
  before_filter :new_hull, :only => [:new, :create]
  before_action :reject_empty_params, only: [:create, :update]

  before_action :set_hull, except: [:index, :create, :filter, :new]
  before_action :set_computer, except: [:new, :edit, :create, :destroy ]
  append_before_action :consider_computer, only: [:index, :filter]

  load_and_authorize_resource

  [:form_factors, :power_supply_position, :number_of_storage_slots, :number_of_optical_drives,
   :number_of_front_usb].each do |field_symbol|
    scope_symbol = "with_#{field_symbol}".to_sym
    has_scope scope_symbol, type: :array, only: :filter do |controller, scope, values|
      (values.all? &:blank?) ? scope : scope.send(scope_symbol, values)
    end
  end

  [:power_supply_power, :video_card_max_length, :cpu_cooler_max_height].each do |field_symbol|
    has_scope "with_#{field_symbol}".to_sym, using: [:min, :max], type: :hash, only: :filter
  end

  [:front_usb3, :front_mic, :front_headphone, :front_fire_wire].each do |field_symbol|
    has_scope "with_#{field_symbol}".to_sym, type: :boolean, only: :filter
  end


  # GET /hulls
  # GET /hulls.json
  def index
    @hulls = apply_scopes(@hulls).all.page(params[:page])
    @filter_values = @hulls.filter_values
  end

  def filter
    @filter_values = @hulls.filter_values
    @hulls = apply_scopes(@hulls).all.page(params[:page])
    render :index
  end

  # GET /hulls/1
  # GET /hulls/1.json
  def show
  end

  # GET /hulls/new
  def new
    @hull = Hull.new
  end

  # GET /hulls/1/edit
  def edit
  end

  # POST /hulls
  # POST /hulls.json
  def create
    @hull = Hull.new(hull_params)

    respond_to do |format|
      if @hull.save
        format.html { redirect_to hulls_path, notice: 'Hull was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hull }
      else
        format.html { render action: 'new' }
        format.json { render json: @hull.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hulls/1
  # PATCH/PUT /hulls/1.json
  def update
    respond_to do |format|
      if @hull.update(hull_params)
        format.html { redirect_to hulls_path, notice: 'Hull was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hull.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hulls/1
  # DELETE /hulls/1.json
  def destroy
    @hull.destroy
    respond_to do |format|
      format.html { redirect_to hulls_url }
      format.json { head :no_content }
    end
  end

  def add_to
    authorize! :add_to, @computer
    @computer.hull = @hull
    @computer.power_supply = @hull.power_supply if @hull.power_supply.present?
    if @computer.save!
      redirect_to edit_computer_url(@computer)
    else
      flash[:alert] = "Can't add Hull to configuration"
    end
  end

  def remove_from
    authorize! :remove_from, @computer
    @computer.power_supply = nil if @computer.power_supply == @hull.power_supply
    @computer.hull = nil
    @computer.save
    redirect_to edit_computer_url(@computer)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_hull
    @hull = Hull.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def hull_params
    params.require(:hull).permit(HardwareController::PERMITTED_PARAMS + [:power_supply_power, :power_supply_position,
                                 :number_of_storage_slots, :number_of_optical_drives, :number_of_front_usb, :front_usb3,
                                 :front_mic, :front_headphone, :front_fire_wire, :video_card_max_length,
                                 :cpu_cooler_max_height, form_factors: []])
  end

  def reject_empty_params
    params[:hull][:form_factors].reject!(&:blank?) if params[:hull][:form_factors].present?
  end

  def consider_computer
    @hulls = Hull.computer_compatible(@computer)
  end

  def set_computer
    @computer = Computer.find(params[:computer_id]) if params[:computer_id].present?
  end

  def new_hull
    @hull = Hull.new()
  end

  def parse_from_services
    if params[:commit] == 'Fetch'
      @hull = Hull.find(params[:id]) if params[:id]
      @hull ||= Hull.new(hull_params)
      @hull.parse_from_services
      render :edit
    end
  end
end

app/views/hulls/_filter_form.html.haml
= simple_form_for '', url: [:filter, (:computer if @computer.present?), :hulls] do |f|
  - Hull::ORDERED_FIELDS_FOR_FILTERS.each do |field_symbol|
    - if @filter_values[field_symbol].present?
      - values = @filter_values[field_symbol]
      - scope_symbol = "with_#{field_symbol.to_s}".to_sym
      - if [:amazon_price, :power_supply_power, :video_card_max_length, :cpu_cooler_max_width].include? field_symbol

        %div{id: scope_symbol.to_s, class: 'range-input'}
          = render 'shared/range_filter_inputs', f: f, scope_symbol: scope_symbol, values: values,
           input_label: t(field_symbol, scope: 'simple_form.labels.hull')

      - elsif [:front_usb3, :front_mic, :front_headphone, :front_fire_wire, :power_supply_down].include? field_symbol
        %div{id: scope_symbol.to_s}= f.input scope_symbol,
          as: :boolean,
          input_html: { checked: current_scopes[scope_symbol].present? },
          label: false,
          inline_label: t(field_symbol, scope: 'simple_form.labels.motherboard'),
          required: false

      - else
        %div{id: scope_symbol.to_s}= f.input scope_symbol,
          collection: values.collect { |v| [v.to_s, v] },
          as: :check_boxes,
          label:  (content_tag :span, t(field_symbol, scope: 'simple_form.labels.hull'), class: 'collapsible',
            data: {toggle: 'collapse', target: "._#{scope_symbol.to_s} .controls"}),
          checked: current_scopes[scope_symbol],
          required: false,
          wrapper:  current_scopes[scope_symbol].present? && current_scopes[scope_symbol].length > 1 ? :expand : :collapse

  .form-actions
    = f.submit 'Filter', class: 'btn btn-primary', id: 'filter-button'
    = link_to 'Reset filters', [@computer, :hulls] , class: 'btn btn-warning pull-right'

app/views/hulls/_form.html.haml
= simple_form_for @hull do |f|
  - if @hull.errors.any?
    #error_explanation
      %h2
        = pluralize(@hull.errors.count, "error")
        prohibited this Hull from being saved:
      %ul
        - @hull.errors.full_messages.each do |msg|
          %li= msg

  .inputs
    = render 'shared/hardware_form', f: f, hardware: @hull

    .row
      .col-md-3
        = f.input :form_factors, collection: Motherboard::POSSIBLE_FORM_FACTORS, as: :check_boxes
      .col-md-3
        = f.input :power_supply_power
      .col-md-3
        = f.input :power_supply_position, collection: Hull::POWER_SUPPLY_POSITIONS, label: t('simple_form.labels.hull.power_supply_position')
      .col-md-3
        = f.input :number_of_storage_slots
    .row
      .col-md-3
        = f.input :number_of_optical_drives
      .col-md-3
        = f.input :number_of_front_usb
      .col-md-3
        = f.input :front_usb3, as: :boolean, label: false, inline_label: t('simple_form.labels.hull.front_usb3')
      .col-md-3
        = f.input :front_mic, as: :boolean, label: false, inline_label: t('simple_form.labels.hull.front_mic')

    .row
      .col-md-3
        = f.input :front_headphone, as: :boolean, label: false, inline_label: t('simple_form.labels.hull.front_headphone')
      .col-md-3
        = f.input :front_fire_wire, as: :boolean, label: false, inline_label: t('simple_form.labels.hull.front_fire_wire')
      .col-md-3
        = f.input :video_card_max_length
      .col-md-3
        = f.input :cpu_cooler_max_height

    .row
      .col-md-3
        %br
        = f.submit

app/views/hulls/_hull_item.html.haml
- if hull.present?
  - if @computer
    - could_be_added = @computer.hull.nil?
    - could_be_removed = @computer.hull == hull

  = block_to_partial 'shared/hardware_item', could_be_added: could_be_added,
                                             could_be_removed: could_be_removed,
                                             hardware: hull do

    = hull.form_factors * ', '
    = "#{hull.power_supply_power} W Power Supply, " if hull.power_supply.present?
    #{hull.power_supply_position} Power Supply position
    #{hull.number_of_front_usb}x Front USBs
    = hull.front_usb3 ? 'Has front USB 3.0, ' : ''
    = hull.front_mic ? 'Has front microphone, ' : ''
    = hull.front_headphone ? 'Has front headphone, ' : ''
    = hull.front_fire_wire ? 'Has front FireWire, ' : ''
    = 'Power Supply on the bottom, ' if hull.power_supply_down

    = hull.video_card_max_length.to_s + ' mm max Video Card length ' if hull.video_card_max_length.present?
    = hull.cpu_cooler_max_height.to_s + ' mm max CPU Cooler height ' if hull.cpu_cooler_max_height.present?

    #{hull.number_of_storage_slots}x storage bays
    #{hull.number_of_optical_drives}x optical drive bays

app/views/hulls/edit.html.haml
%h1 Editing hull
= render 'form'

= link_to 'Back', hulls_path

app/views/hulls/index.html.haml
.row
  #list-content.col-md-9
    = back_link(@computer)

    #guide.panel.panel-default
      .panel-body
        %h1 Selection guide
        = render 'pages/hulls_guide'

    - if @hulls.blank?
      = no_hardware_message('Hulls')
    - else
      = page_entries_info @hulls
      - @hulls.each do |hull|
        = render 'hull_item', hull: hull

    = paginate @hulls

  .col-md-3
    %button#toggle-guide.btn.btn-info
      Show Guide
    = link_to('New Hull', new_hull_path, class: 'btn btn-primary') if can? :create, Hull
    - if @filter_values.present?
      = render 'shared/order_by'
      .row
        .col-md-12
          #filters.panel.panel-default
            .panel-heading
              %h3.panel-title Filters
            .panel-body
              =render 'filter_form'

app/views/hulls/new.html.haml
%h1 New hull
= render 'form'
= link_to 'Back', hulls_path

app/views/hulls/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_hull_path(@hull)
|
\#{link_to 'Back', hulls_path}