config/routes.rb
Fithardware::Application.routes.draw do
  root to: "computers#index"
  get "guides", to: "pages#guides"
  get "about", to: "pages#about"

  devise_for :users

  resources :hulls,
            :power_supplies,
            :rams,
            :hdds,
            :ssds,
            :optical_drives,
            :motherboards,
            :cpus,
            :cpu_coolers,
            :video_cards do
    collection do
      post :filter
      get :filter
    end
  end

  resources :users do
    resources :computers
  end

  resources :computers do
    resources :hulls,
              :power_supplies,
              :rams,
              :hdds,
              :ssds,
              :optical_drives,
              :motherboards,
              :cpus,
              :cpu_coolers,
              :video_cards,
              only: [:index, :filter] do

      member do
        post :add_to
        post :remove_from
      end
      collection do
        post :filter
        get  :filter
      end
    end

    member do
      post :publish
    end
  end

  

end

app/models/computer.rb
class Computer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes

  MARGIN_OF_POWER_SUPPLY_SAFETY = 1.2
  MARGIN_OF_SIZE_FITTING = 0.9

  field :violations, type: Array, default: []
  field :state, default: 'new'
  field :name, type: String
  field :description, type: String, default: 'Description is empty'
  field :power_consumption, type: Integer, default: 0
  field :hackintosh_compatible, type: Mongoid::Boolean, default: false
  field :quiet, type: Mongoid::Boolean, default: false
  field :profi_mode, type: Mongoid::Boolean, default: false
  field :amazon_price, type: Float, default: 0.00
  field :hardware_counter, type: Integer, default: 1
  field :weight, type: Float, default: 0

  belongs_to              :hull
  belongs_to              :motherboard
  belongs_to              :power_supply
  has_one                 :cpus, class_name: 'PackSet', inverse_of: :cpus
  has_one                 :cpu_coolers, class_name: 'PackSet', inverse_of: :cpu_coolers
  has_one                 :rams, class_name: 'PackSet', inverse_of: :rams
  has_one                 :ssds, class_name: 'PackSet', inverse_of: :ssds
  has_one                 :hdds, class_name: 'PackSet', inverse_of: :hdds
  has_one                 :video_cards, class_name: 'PackSet', inverse_of: :video_cards
  has_one                 :optical_drives, class_name: 'PackSet', inverse_of: :optical_drives

  belongs_to :user

  scope :published, ->() { where(:state => 'published') }

  state_machine :state, initial: :new do

    event :publish do
      transition :new => :published
      transition :published => same
    end

    event :unvalidate do
      transition any => :new
    end

    state :published do
      validates_presence_of :rams,
                            :hull,
                            :cpus,
                            :motherboard,
                            :power_supply,
                            :power_consumption

      validate              :cpus_validator
      validate              :form_factor_validator
      validate              :storage_validator
      validate              :rams_validator
      validate              :power_validator
      validate              :videocards_validator
      validate              :video_validator
      validate              :sizes_validator
      validate              :cooling_validator
    end
  end

  before_save :update_counters
  after_validation :check_state

  set_callback(:create, :before) do |document|

    document.create_rams
    document.create_cpus
    document.create_ssds
    document.create_hdds
    document.create_video_cards
    document.create_optical_drives
    document.create_cpu_coolers
  end

  def free_sockets
    if motherboard.present?
      cpus.present? ? (motherboard.number_of_sockets - cpus.count) : motherboard.number_of_sockets
    else
      1
    end
  end

  def free_cpu_cooler_places
    if motherboard.present?
      cpu_coolers.present? ? (motherboard.number_of_sockets - cpu_coolers.count) : motherboard.number_of_sockets
    else
      1
    end
  end

  def free_ram_slots
    if motherboard.present?
      rams.present? ? (motherboard.number_of_ram_slots - rams.count) : motherboard.number_of_ram_slots
    else
      1
    end
  end

  def ram_total_size
    rams.reduce(0) { |val, ram| val + ram.capacity}
  end

  def free_ram_size
    free_size = 10000000
    if motherboard.present?
      free_size = motherboard.max_ram_total_size
      free_size -= ram_total_size
    end
    return free_size
  end

  def free_drive_slots
    if motherboard.present?
      if hull.present?
        number_of_free_slots =  [(motherboard.number_of_sata2_ports + motherboard.number_of_sata3_ports),
                                 hull.number_of_storage_slots].min
      else
        number_of_free_slots = motherboard.number_of_sata2_ports + motherboard.number_of_sata3_ports
      end
    elsif hull.present?
      number_of_free_slots = hull.number_of_storage_slots
    else
      return 1
    end

    return number_of_free_slots - necessary_sata_ports.to_i
  end

  def free_optical_drive_places
    places_in_hull = hull.present? ? (hull.number_of_optical_drives - optical_drives.count) : 1
    return [places_in_hull, free_drive_slots].min
  end

  def necessary_sata_ports
    [ssds, hdds, optical_drives].reduce(0) { |val, collection| val + collection.count}
  end

  def free_video_card_slots
    if motherboard.present?
      video_cards.present? ? (motherboard.number_of_pcie_x16_slots - video_cards.count) : (motherboard.number_of_pcie_x16_slots)
    else
      1
    end
  end

  def calculate_power_consumption
    self.power_consumption = motherboard.present? ? motherboard.power_consumption : 0
    
    [cpus, ssds, hdds, optical_drives, rams, video_cards].each do |hardware_set|
      if hardware_set.present?
        hardware_set.each { |consumer| self.power_consumption += consumer.power_consumption }
      end
    end

    self.power_consumption *= MARGIN_OF_POWER_SUPPLY_SAFETY
  end

  def necessary_6_pin
    video_cards.to_a.reduce(0) {|total, vc| total + vc.number_of_6_pin }
  end

  def necessary_8_pin
    video_cards.to_a.reduce(0) {|total, vc| total + vc.number_of_8_pin }
  end


  private

  def sizes_validator
    if hull.present?
      if video_cards.present?
        video_cards.each do |vc|
          errors.add(:video_cards, 'Video card is wider than case') if vc.unpacked_width * MARGIN_OF_SIZE_FITTING >= hull.unpacked_width
          errors.add(:video_cards, 'Video card is longer than case') if vc.unpacked_length >= hull.video_card_max_length
        end
      end

      fitting_cpu_coolers = 0
      uncooled_cpus =  0

      if cpus.present?
        cpus.each do |cpu|
          uncooled_cpus += 1 if ((cpu.unpacked_height > hull.cpu_cooler_max_height) || (cpu.complectation == 'Tray'))
        end
      end

      if cpu_coolers.present?
        cpu_coolers.each { |cc| fitting_cpu_coolers += 1 if cc.unpacked_height < hull.cpu_cooler_max_height * MARGIN_OF_SIZE_FITTING }
      end

      errors.add(:cpu_coolers, 'Not enough cpu coolers of fitting size') if fitting_cpu_coolers < uncooled_cpus
    end
  end

  def cooling_validator
    uncooled_cpus = 0

    if cpus.present?
      cpus.each { |cpu| uncooled_cpus += 1 if cpu.complectation == 'Tray' }
    end

    errors.add(:cpu_coolers, 'Computer has a cpu without cooling system') if cpu_coolers.count < uncooled_cpus

    if cpu_coolers.present? && cpus.present?
      cpu_coolers.each do |cpu_cooler|
        unless cpu_cooler.sockets.include? cpus.first.socket
          errors.add(:cpu_coolers, "CPU cooler #{cpu_cooler.product_name} doesn't support socket #{cpus.first.socket}")
        end
      end
    end
  end

  def presence_validator
    return true if profi_mode
    rams.any? && hull.present? && cpu.present? && motherboard.present? && power_supply.present?
  end

  def storage_validator
    unless profi_mode
      errors.add(:hdds, "Must have at least one storage") if ssds.empty? && hdds.empty?
      if motherboard
        if (motherboard.number_of_sata2_ports + motherboard.number_of_sata3_ports) < necessary_sata_ports
          errors.add(:motherboard, "Not enough SATA ports")
        end
      end
    end
  end

  def rams_validator
    if motherboard && rams.present?
      rams.each do |ram|
        errors.add(:rams, "Motherboard doesn't support this generation of RAM") unless motherboard.ram_generations.include? ram.generation
        errors.add(:rams, "All RAMs must have the same generation") unless ram.generation == rams.first.generation
        errors.add(:rams, "All RAMs must have the same frequency") unless ram.frequency == rams.first.frequency
      end
      errors.add(:rams, "Motherboard doesn't have so many RAM slots") if motherboard.number_of_ram_slots < rams.count
      errors.add(:rams, "Motherboard doesn't support so big ram capacity") if free_ram_size < 0
      errors.add(:rams, "RAM can not be run with standart frequencies") if motherboard.max_ram_frequency < rams.first.frequency
    end
  end

  def cpus_validator
    if motherboard && cpus.present?
      errors.add(:cpus, "Not enough cpu sockets") if cpus.count > motherboard.number_of_sockets
      cpus.each do |cpu|
        errors.add(:cpu, "Processor socket type mismatch") unless cpu.socket == motherboard.socket
      end
    end
  end

  def form_factor_validator
    if hull && motherboard
      errors.add(:hull, "Motherboard doesn't fit case") unless hull.form_factors.to_a.include? motherboard.form_factor
    end
  end

  def power_validator
    if power_supply

      errors.add(:power_supply, "Not enough power for system. Select more powerful power supply") if power_consumption > power_supply.power


      required_universal_connectors = (necessary_6_pin - power_supply.number_of_6_pin) + (necessary_8_pin - power_supply.number_of_8_pin)
      errors.add(:power_supply, "Not enough pin connectors") if (power_supply.number_of_6_2_pin < required_universal_connectors)
    end
  end

  def videocards_validator
    if video_cards.present? && motherboard
      cards = video_cards.to_a
      errors.add(:motherboard, "Motherboard doesn't have enough video card slots") if cards.count > motherboard.number_of_pcie_x16_slots

      if cards.count > 1 && !profi_mode
        if motherboard.supported_multi_gpus.blank?
          errors.add(:motherboard, 'Motherboard doesn\'t support video cards aggregation')
        else
          tmp = video_cards.first.multi_gpu_technology
          cards.each do |video_card|
            errors.add(:video_cards, "Uncompatible multi-GPU support between motherboard and videocard") unless motherboard.supported_multi_gpus.include? video_card.multi_gpu_technology
            errors.add(:video_cards, "Uncompatible multi-GPU support between videocards") unless video_card.multi_gpu_technology == tmp
          end
        end
      elsif cards.count > 1 && profi_mode

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_configuration, only: [:show, :edit, :update, :destroy, :publish]

  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all
    @computers = @computers.where(:user => params[:user_id]) if params[:user_id]
    @computers = @computers.page(params[:page])
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
    @computer.user = current_user
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)

    respond_to do |format|
      if verify_recaptcha(model: @computer) && @computer.save!
        format.html { redirect_to edit_computer_path(@computer), notice: 'Computer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @computer }
      else
        format.html { render action: 'new' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update_attributes(computer_params)
        format.html { render action: 'edit', notice: 'Computer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @computer.publish
    if @computer.save && @computer.published?
      flash[:notice] = 'Successfully published'
      render 'show'
    else
      render 'edit'
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuration
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit([:description, :hackintosh_compatible, :quiet])
    end
end

app/views/computers/_computer_features.html.haml
.row.hardware-select
  .col-md-2.hardware-type#description
    Description
  .col-md-9
    = f.input :description, label: false, input_html: {size: 105}, disabled: !can?(:edit, @computer)

.row.hardware-select
  .col-md-2.hardware-type#features
    Pro features
  .col-md-8
    .row
      .col-md-7
        = f.input :hackintosh_compatible,
                  inline_label: 'Hackintosh compatible',
                  as: :boolean,
                  label: false,
                  disabled: !can?(:edit, @computer)
      .col-md-5
        = f.input :quiet,
                  inline_label: 'Quiet (noise < 20 dB)',
                  as: :boolean,
                  label: false,
                  disabled: !can?(:edit, @computer)

  - if can?(:edit, @computer) && !@computer.new_record?
    .col-md-2
      = f.submit 'Apply', class: 'btn btn-success'

app/views/computers/_computer_item.html.haml
- if computer.present?
  %p
    .hardware-container
      .row
        .col-md-2
          = link_to((image_tag computer.hull.image.thumb.url, class: 'img-thumbnail'), computer) if computer.hull.present?
        .col-md-7
          %h4.hardware-title
            = link_to (computer.description.present? ? computer.description : 'Description is empty'), computer_path(computer)
          %p.hardware-standard-features
            = computer.hardware_counter.to_s + ' Items, '
            = computer.weight.to_s + ' kg'
            = verified_span(computer)
          %p.hardware-features
            = pack_set_hardware(computer.cpus)
            = pack_set_hardware(computer.cpu_coolers)
            = (hardware_title(computer.motherboard) + ', ') if computer.motherboard.present?
            = pack_set_hardware(computer.rams)
            = pack_set_hardware(computer.ssds)
            = pack_set_hardware(computer.ssds)
            = pack_set_hardware(computer.optical_drives)
            = pack_set_hardware(computer.video_cards)
            = (hardware_title(computer.power_supply) + ', ') if computer.power_supply.present?
            = hardware_title(computer.hull) if computer.hull.present?

        .col-md-3
          %p.market
            %span.price
              = computer.amazon_price.to_s + ' $'

          %p
            - if can? :edit, computer
              .btn-group
                = link_to 'Verify', [:publish, computer], method: :post, class: 'btn btn-warning'
                - if can? :delete, computer
                  = link_to 'Delete', computer,
                             method: :delete, class: 'btn btn-danger',
                             data: { confirm: 'Do you really want to delete this computer?' }

app/views/computers/_form.html.haml
- if @computer.violations.any?
  .row
    .col-md-4.col-md-offset-4
      #error_explanation
        %h2
          = pluralize(@computer.violations.count, "error")
          made this computer invalid:
        %ul
          - @computer.violations.each do |msg|
            %li= msg

= render 'responsibility'

.row.hardware-select#cpus
  .col-md-2.hardware-type
    CPU
  .col-md-9
    - if @computer.cpus.present?
      - @computer.cpus.each do |cpu|
        = render 'cpus/cpu_item', cpu: cpu
      - if @computer.free_sockets > 0 && can?(:add_to, @computer)
        %p
          = add_hardware_row 'CPU', computer_cpus_path(@computer) do
            #{@computer.free_sockets} free sockets left
    - else
      = add_hardware_row 'CPU', computer_cpus_path(@computer) do
        - t('computer.explain.cpu')

.row.hardware-select#cpu_coolers
  .col-md-2.hardware-type
    CPU Cooler
  .col-md-9
    - if @computer.cpu_coolers.present?
      - @computer.cpu_coolers.each do |cpu_cooler|
        = render 'cpu_coolers/cpu_cooler_item', cpu_cooler: cpu_cooler
      - if @computer.free_cpu_cooler_places > 0
        %p
          = add_hardware_row 'CPU Cooler', computer_cpu_coolers_path(@computer) do
            #{@computer.free_cpu_cooler_places} free cooler places left

    - else
      = add_hardware_row 'CPU Cooler', computer_cpu_coolers_path(@computer) do
        - t('computer.explain.cpu_cooler')

.row.hardware-select#motherboards
  .col-md-2.hardware-type
    Motherboard
  .col-md-9
    - if @computer.motherboard.present?
      = render 'motherboards/motherboard_item', motherboard: @computer.motherboard
    - else
      = add_hardware_row 'Motherboard', computer_motherboards_path(@computer) do
        = t('computer.explain.motherboard')

.row.hardware-select#rams
  .col-md-2.hardware-type
    RAM
  .col-md-9
    - if @computer.rams.present?
      - @computer.rams.each do |ram|
        = render 'rams/ram_item', ram: ram
      - if @computer.free_ram_slots > 0 && can?(:add_to, @computer)
        %p
          = add_hardware_row 'RAM', computer_rams_path(@computer) do
            #{@computer.free_ram_slots} free slots left

    - else
      = add_hardware_row 'RAM', computer_rams_path(@computer) do
        - t('computer.explain.ram')

.row.hardware-select#hdds
  .col-md-2.hardware-type
    HDD
  .col-md-9
    - if @computer.hdds.present?
      - @computer.hdds.each do |hdd|
        = render 'hdds/hdd_item', hdd: hdd
      - if @computer.free_drive_slots > 0 && can?(:add_to, @computer)
        %p
          = add_hardware_row 'HDD', computer_hdds_path(@computer) do
            #{@computer.free_drive_slots} free sata ports left

    - else
      = add_hardware_row 'HDD', computer_hdds_path(@computer) do
        - t('computer.explain.hdd')

.row.hardware-select#ssds
  .col-md-2.hardware-type
    SSD
  .col-md-9
    - if @computer.ssds.present?
      - @computer.ssds.each do |ssd|
        = render 'ssds/ssd_item', ssd: ssd

      - if @computer.free_drive_slots > 0 && can?(:add_to, @computer)
        %p
          = add_hardware_row 'SSD', computer_ssds_path(@computer) do
            #{@computer.free_drive_slots} free sata ports left

    - else
      = add_hardware_row 'SSD', computer_ssds_path(@computer) do
        - t('computer.explain.ssd')

.row.hardware-select#optical_drives
  .col-md-2.hardware-type
    Optical Drive
  .col-md-9
    - if @computer.optical_drives.present?
      - @computer.optical_drives.each do |optical_drive|
        = render 'optical_drives/optical_drive_item', optical_drive: optical_drive

      - if @computer.free_optical_drive_places > 0 && can?(:add_to, @computer)
        %p
          = add_hardware_row 'Optical Drive', computer_optical_drives_path(@computer) do
            #{@computer.free_drive_slots} free sata ports left

    - else
      = add_hardware_row 'Optical Drive', computer_optical_drives_path(@computer) do
        - t('computer.explain.optical_drive')

.row.hardware-select#video_cards
  .col-md-2.hardware-type
    Video Card
  .col-md-9
    - if @computer.video_cards.present?
      - @computer.video_cards.each do |video_card|
        = render 'video_cards/video_card_item', video_card: video_card

      - if @computer.free_video_card_slots > 0 && can?(:add_to, @computer)
        %p
          = add_hardware_row 'Video Card', computer_video_cards_path(@computer) do
            #{@computer.free_video_card_slots} free video card slots left

    - else
      = add_hardware_row 'Video Card', computer_video_cards_path(@computer) do
        - t('computer.explain.video_card')

.row.hardware-select#hulls
  .col-md-2.hardware-type
    Case
  .col-md-9
    - if @computer.hull.present?
      = render 'hulls/hull_item', hull: @computer.hull

    - else
      = add_hardware_row 'Case', computer_hulls_path(@computer) do
        - t('computer.explain.hull')

.row.hardware-select#power_supplies
  .col-md-2.hardware-type
    Power Supply
  .col-md-9
    - if @computer.power_supply.present?
      = render 'power_supplies/power_supply_item', power_supply: @computer.power_supply

    - else
      = add_hardware_row 'Power Supply', computer_power_supplies_path(@computer) do
        - t('computer.explain.power_supply')

.row.hardware-select#total
  .col-md-2.hardware-type
    Total
  .col-md-9
    = render 'computer_item', computer: @computer

app/views/computers/_responsibility.html.haml
.row
  .col-md-12.text-danger.text-center
    This is a testing version of site. We don't take any responsibility for accuracy of provided information and workability
    of selected hardware.

app/views/computers/edit.html.haml
.row-fluid
  .col-md-12
    = content_for :top do
      = simple_form_for @computer do |f|
        .container-fluid
          .row.features-inputs
            = render 'computer_features', f: f

    = render 'form'

    = link_to 'Short view', @computer
    |
    = link_to 'All computers', computers_path
    |
    = link_to 'How to assemble', 'http://en.wikibooks.org/wiki/How_To_Assemble_A_Desktop_PC/Assembly', target: :blank

app/views/computers/index.html.haml
%h1 Recent computers

- if @computers.present?
  = page_entries_info @computers

  - @computers.each do |computer|
    = render 'computer_item', computer: computer

  = paginate @computers

app/views/computers/new.html.haml
.row-fluid
  .col-md-12
    = simple_form_for @computer do |f|
      = render 'computer_features', f: f

      .row.hardware-select
        .col-md-8.col-md-offset-2
          .row
            .col-md-7
              = recaptcha_tags
            .col-md-5
              = f.button :submit, 'Create', class: 'btn btn-success'

    = link_to 'To configurations list', computers_path

app/views/computers/show.html.haml
= render 'responsibility'

%div{class: (@computer.published? ? 'panel panel-success' : 'panel panel-warning')}
  .panel-heading
    .panel-title
      = @computer.published? ? 'Verified' : 'Unverified'
  .panel-body

    - if @computer.motherboard.present?
      %h4= 'Motherboard'
      = hardware_title @computer.motherboard

    - if @computer.cpus.present?
      %h4= pluralize(@computer.cpus.count, 'CPU')
      = pack_set_hardware(@computer.cpus, true)

    - if @computer.cpu_coolers.present?
      %h4= pluralize(@computer.cpu_coolers.count, 'CPU Cooler')
      = pack_set_hardware(@computer.cpu_coolers, true)

    - if @computer.rams.present?
      %h4= pluralize(@computer.rams.count, 'RAM')
      = pack_set_hardware(@computer.rams, true)

    - if @computer.hdds.present?
      %h4= pluralize(@computer.hdds.count, 'HDD')
      = pack_set_hardware(@computer.hdds, true)

    - if @computer.ssds.present?
      %h4= pluralize(@computer.ssds.count, 'SSD')
      = pack_set_hardware(@computer.ssds, true)

    - if @computer.optical_drives.present?
      %h4= pluralize(@computer.optical_drives.count, 'Optical Drive')
      = pack_set_hardware(@computer.optical_drives, true)

    - if @computer.video_cards.present?
      %h4= pluralize(@computer.video_cards.count, 'Video Card')
      = pack_set_hardware(@computer.video_cards, true)

    - if @computer.hull.present?
      %h4= 'Case'
      = hardware_title @computer.hull

    - if @computer.power_supply.present?
      %h4= 'Power Supply'
      = hardware_title @computer.power_supply

= link_to 'Details', edit_computer_path(@computer)
|
= link_to 'Existing configurations', computers_path
|
= link_to 'How to assemble', 'http://en.wikibooks.org/wiki/How_To_Assemble_A_Desktop_PC/Assembly', target: :blank